'use client';

import React from 'react';
import { ReportDownloadRequest, ReportPreviewData } from '@/types/report.types';
import AitsLogo from '@/components/common/AitsLogo';
import { generateReportReferenceNumber } from '@/utils/report-export/report-reference';
import { formatNumber } from '@/utils/report.utils';

interface ReportPrintLayoutProps {
  request: ReportDownloadRequest;
  previewData: ReportPreviewData;
}

const COLUMN_HEADER_MAP: Record<string, string> = {
  animalTag: 'Tag ID',
  animalName: 'Animal Name',
  farmName: 'Facility / Location',
  morningYield: 'Morning (L)',
  eveningYield: 'Evening (L)',
  totalYield: 'Total (L)',
  qualityStatus: 'Quality',
  recordedBy: 'Recorder / Verified By',
  caseDate: 'Case Date',
  diagnosis: 'Diagnosis / Condition',
  severity: 'Severity',
  treatmentStatus: 'Treatment Status',
  treatment: 'Treatment / Protocol',
  treatmentStartDate: 'Treatment Start',
  treatmentEndDate: 'Treatment End',
  veterinarian: 'Attending Vet',
  clinicalRemarks: 'Clinical Remarks',
  serviceDate: 'Service Date',
  breedingMethod: 'Method',
  technician: 'Technician',
  sireInfo: 'Sire / Straw',
  pregnancyStatus: 'Pregnancy',
  expectedCalvingDate: 'Due Date',
  calvingOutcome: 'Calving Outcome',
  calvingStatus: 'Calving Status',
  dateTime: 'Date & Time',
  eventType: 'Event Category',
  eventDescription: 'Event Audit Details',
  feedingSession: 'Session Shift',
  feedCategory: 'Feed Category',
  feedType: 'Feed Formula',
  actualQuantity: 'Intake (kg)',
  quantity: 'Quantity (kg)',
  unit: 'Unit',
  milkYield: 'Milk Yield (L)',
  feedEfficiency: 'Feed Efficiency (L/kg)',
  remarks: 'Remarks / Notes',
  originFarm: 'Origin Facility',
  destinationFarm: 'Destination Facility',
  departureDateTime: 'Dispatched At',
  arrivalDateTime: 'Arrival Time',
  movementReason: 'Movement Reason',
  transportInfo: 'Hauler & Transport',
  movementStatus: 'Transit Status',
  authorizedBy: 'Authorized By',
  milestoneCategory: 'Lifecycle Phase',
  milestoneTitle: 'Milestone / Event',
  milestoneDetails: 'Event Details & Clinical / Movement Notes',
  farmLocation: 'Facility Location',
  notes: 'Operational Notes',
  status: 'Status',
};

function formatHeaderTitle(key: string): string {
  if (COLUMN_HEADER_MAP[key]) return COLUMN_HEADER_MAP[key];
  return key.replace(/([A-Z])/g, ' $1').trim();
}

export const ReportPrintLayout: React.FC<ReportPrintLayoutProps> = ({ request, previewData }) => {
  const refNumber = generateReportReferenceNumber(request.reportType, request.animalId);
  const sampleRows = previewData.sampleRows || [];
  const keys = sampleRows.length > 0 ? Object.keys(sampleRows[0]).filter((k) => k !== 'id') : [];

  return (
    <div className="bg-white text-[#0d0d0d] p-6 md:p-10 font-sans print:p-0 print:text-black">
      {/* Top Emerald Line */}
      <div className="h-1 bg-[#10a37f] w-full mb-6 print:mb-4" />

      {/* Header Section */}
      <div className="flex items-start justify-between pb-6 border-b border-[#e5e5e5]">
        <div className="flex items-center gap-4">
          <AitsLogo variant="full" size="lg" priority />
        </div>
        <div className="text-right text-xs text-[#5d5d5d]">
          <p className="font-bold text-[#0d0d0d]">
            Ref: <span className="font-mono text-[#10a37f]">{refNumber}</span>
          </p>
          <p className="mt-0.5">Date: {previewData.generatedAt}</p>
          <p>Generated By: {previewData.generatedBy}</p>
        </div>
      </div>

      {/* Document Title & Subtitle */}
      <div className="mt-6 mb-6">
        <h1 className="text-xl md:text-2xl font-black tracking-tight text-[#10a37f] uppercase">
          {previewData.title}
        </h1>
        <p className="text-xs text-[#737373] mt-1 font-medium">
          Official Operational Report Document • Animal Identification & Traceability System
        </p>
      </div>

      {/* Metadata & Active Filters Card */}
      <div className="bg-[#f9f9f9] border border-[#e5e5e5] rounded-xl p-4 mb-6 grid grid-cols-2 md:grid-cols-4 gap-4 text-xs">
        <div>
          <span className="block font-bold text-[10px] uppercase text-[#737373]">Farm Scope</span>
          <strong className="text-[#0d0d0d]">{previewData.farmName}</strong>
        </div>
        <div>
          <span className="block font-bold text-[10px] uppercase text-[#737373]">Date Range</span>
          <strong className="text-[#0d0d0d]">{previewData.dateRange}</strong>
        </div>
        <div>
          <span className="block font-bold text-[10px] uppercase text-[#737373]">Target Scope</span>
          <strong className="text-[#0d0d0d]">{previewData.animalName || 'All Assigned Animals'}</strong>
        </div>
        <div>
          <span className="block font-bold text-[10px] uppercase text-[#737373]">Audit Records</span>
          <strong className="text-[#10a37f]">{previewData.recordsCount} Total Records</strong>
        </div>
      </div>

      {/* Summary KPI Cards Grid */}
      {request.includeSummaryCards && previewData.summaryItems.length > 0 && (
        <div className="mb-8">
          <h2 className="text-xs font-extrabold uppercase tracking-wider text-[#0d0d0d] mb-3">
            Executive Metrics Summary
          </h2>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
            {previewData.summaryItems.slice(0, 6).map((item) => (
              <div
                key={item.id}
                className="bg-[#f9f9f9] border border-[#e5e5e5] border-l-4 border-l-[#10a37f] rounded-lg p-3"
              >
                <span className="block text-[10px] font-bold uppercase text-[#737373] truncate">
                  {item.label}
                </span>
                <strong className="text-base font-extrabold text-[#10a37f] block mt-1">
                  {typeof item.value === 'number' ? formatNumber(item.value) : item.value} {item.unit || ''}
                </strong>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Analytical Charts */}
      {request.includeCharts && previewData.chartSummary && previewData.chartSummary.length > 0 && (
        <div className="mb-8 page-break-inside-avoid">
          <h2 className="text-xs font-extrabold uppercase tracking-wider text-[#0d0d0d] mb-3">
            Analytical Visualizations & Trends
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {previewData.chartSummary.map((chart, idx) => (
              <div
                key={idx}
                className="bg-[#f9f9f9] border border-[#e5e5e5] rounded-xl p-4 space-y-2 page-break-inside-avoid"
              >
                <h3 className="text-xs font-bold text-[#10a37f] uppercase">{chart.title}</h3>
                <div className="h-24 bg-white border border-[#e5e5e5] rounded-lg flex flex-col items-center justify-center p-2 text-center">
                  <div className="flex items-end gap-2 h-12 mb-1">
                    {[35, 60, 45, 80, 65, 90, 75].map((h, bIdx) => (
                      <div
                        key={bIdx}
                        className="w-4 bg-[#10a37f] rounded-t-sm"
                        style={{ height: `${h}%` }}
                      />
                    ))}
                  </div>
                  <span className="text-[10px] font-medium text-[#737373]">
                    {chart.dataPointsCount} Verified Data Points Recorded
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Detailed Data Table */}
      {request.includeDetailedTable && sampleRows.length > 0 && (
        <div className="mb-8">
          <h2 className="text-xs font-extrabold uppercase tracking-wider text-[#0d0d0d] mb-3">
            Detailed Audit Data Log ({previewData.recordsCount} Entries)
          </h2>
          <div className="overflow-x-auto border border-[#e5e5e5] rounded-xl">
            <table className="w-full text-left border-collapse text-xs">
              <thead>
                <tr className="bg-[#10a37f] text-white font-bold text-[11px] uppercase">
                  {keys.map((key) => (
                    <th key={key} className="py-2.5 px-3">
                      {formatHeaderTitle(key)}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-[#e5e5e5]">
                {sampleRows.map((row, rIdx) => (
                  <tr key={rIdx} className={rIdx % 2 === 1 ? 'bg-[#f8fafc]' : 'bg-white'}>
                    {keys.map((key) => (
                      <td key={key} className="py-2 px-3 text-[#0d0d0d] text-[11px]">
                        {String(row[key] ?? '')}
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Official Sign-off & Footer */}
      <div className="pt-6 border-t border-[#e5e5e5] mt-10 flex items-end justify-between text-[10.5px] text-[#737373]">
        <div>
          <p className="font-bold text-[#0d0d0d]">Animal Identification & Traceability System (AITS)</p>
          <p>Document Reference: {refNumber} • Generated on {previewData.generatedAt}</p>
        </div>
        <div className="text-right">
          <p className="font-mono text-[#10a37f] font-bold">AITS-OFFICIAL-STAMP-VERIFIED</p>
          {request.includeConfidentialLabel && <p className="font-bold text-rose-600 mt-0.5">CONFIDENTIAL REPORT</p>}
        </div>
      </div>
    </div>
  );
};
