import { jsPDF } from 'jspdf';
import { PDF_COLORS, PDF_FONTS } from '@/constants/report-style.constants';

export interface MetadataOptions {
  doc: jsPDF;
  category: string;
  referenceNumber?: string;
  generatedBy: string;
  generatedDate: string;
  farmName: string;
  animalName?: string;
  dateRange: string;
  recordsCount?: number;
  appliedFilters?: Record<string, string | undefined>;
  startY: number;
}

/**
 * Draws the Report Metadata card grid and Applied Filters bar.
 * Returns the Y position after rendering.
 */
export function drawPdfReportMetadata(options: MetadataOptions): number {
  const {
    doc,
    category,
    referenceNumber,
    generatedBy,
    farmName,
    animalName,
    dateRange,
    recordsCount,
    appliedFilters = {},
    startY,
  } = options;

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const marginX = 14;
  const contentWidth = pageWidth - marginX * 2;
  const maxY = pageHeight - 18;
  let currentY = startY;

  const items: Array<{ label: string; value: string }> = [
    { label: 'Category', value: category },
    { label: 'Farm Scope', value: farmName },
    { label: 'Date Range', value: dateRange },
    { label: 'Generated By', value: generatedBy },
  ];

  if (referenceNumber) {
    items.push({ label: 'Ref Number', value: referenceNumber });
  }
  if (animalName) {
    items.push({ label: 'Animal Target', value: animalName });
  }
  if (recordsCount !== undefined) {
    items.push({ label: 'Audit Records', value: `${recordsCount} Entries` });
  }

  const cardPadding = 3.5;
  const colWidth = contentWidth / 4;
  const rowCount = Math.ceil(items.length / 4);
  const cardHeight = rowCount * 10 + 6;

  if (currentY + cardHeight + 12 > maxY) {
    doc.addPage();
    currentY = 20;
  }

  // Draw Container Box
  doc.setFillColor(...PDF_COLORS.cardBgRgb);
  doc.setDrawColor(...PDF_COLORS.borderRgb);
  doc.setLineWidth(0.3);
  doc.roundedRect(marginX, currentY, contentWidth, cardHeight, 1.5, 1.5, 'FD');

  // Draw 2-row metadata grid inside the container box
  let itemX = marginX + cardPadding;
  let itemY = currentY + 5;

  items.forEach((item, idx) => {
    if (idx > 0 && idx % 4 === 0) {
      itemX = marginX + cardPadding;
      itemY += 10;
    }

    doc.setFont(PDF_FONTS.family, 'bold');
    doc.setFontSize(7);
    doc.setTextColor(...PDF_COLORS.textMutedRgb);
    doc.text(item.label.toUpperCase(), itemX, itemY);

    doc.setFont(PDF_FONTS.family, 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(...PDF_COLORS.textDarkRgb);

    // Truncate long value string if needed
    const truncatedVal = item.value.length > 26 ? `${item.value.slice(0, 24)}...` : item.value;
    doc.text(truncatedVal, itemX, itemY + 4.5);

    itemX += colWidth;
  });

  currentY += cardHeight + 4;

  // Applied Filters Bar
  doc.setFont(PDF_FONTS.family, 'bold');
  doc.setFontSize(7.5);
  doc.setTextColor(...PDF_COLORS.textMutedRgb);
  doc.text('APPLIED FILTERS: ', marginX, currentY);

  const activeFilterPairs: string[] = [];
  Object.entries(appliedFilters).forEach(([k, v]) => {
    if (v && v !== 'ALL' && v !== 'All' && !v.includes('undefined')) {
      activeFilterPairs.push(`${k}: ${v}`);
    }
  });

  const filterStr =
    activeFilterPairs.length > 0
      ? activeFilterPairs.join('  |  ')
      : 'All available records for the selected period';

  doc.setFont(PDF_FONTS.family, 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(...PDF_COLORS.textDarkRgb);
  const splitFilter = doc.splitTextToSize(filterStr, contentWidth - 30);
  doc.text(splitFilter, marginX + 28, currentY);

  currentY += splitFilter.length * 3.5 + 4;

  return currentY;
}
